### ISSUE TITLE
Locked up my system

### ISSUE THREAD

**Issue by Ralsei-x64** [Not-Baguette/WS2P#1]
I tried the software’s firewall capabilities. There was no prompt to choose a password, I cannot unlock it and my system is now bricked.

**Comment by Ralsei-x64** [comment]
Update: I digged a little through the source code, The password was “I love Mei”

**Comment by Not-Baguette** [comment]
Nice job lol

**Comment by Not-Baguette** [comment]
The firewall capability is meant to be time-limited and will remove it by itself, you can set your own password on the code and rebuild it yourself

**Comment by Ralsei-x64** [comment]
> The firewall capability is meant to be time-limited and will remove it by itself, you can set your own password on the code and rebuild it yourself

I did try that. I set the timer for 1 minute. There seemed to be a bug which completely rendered the timer useless.

**Comment by Not-Baguette** [comment]
I see, I'll try experimenting it more and see if I can find the issue

**Comment by Not-Baguette** [comment]
Hi! So I managed to find the issue and managed to fix it, it's still not compiled yet though (Will soon), Thank you for reporting this issue!
